-- Clean start (opcional em dev)
DROP SCHEMA IF EXISTS POSTMORTEM;

-- Schema com UTF8 total
CREATE SCHEMA POSTMORTEM
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_0900_ai_ci;

USE
POSTMORTEM;

-- =========================
-- USERS
-- =========================
CREATE TABLE USER_ACCOUNT
(
    ID_USER_ACCOUNT BIGINT       NOT NULL AUTO_INCREMENT COMMENT 'Primary key.',
    PROVIDER        ENUM('LOCAL','GOOGLE','GITHUB','SAML') NOT NULL DEFAULT 'LOCAL' COMMENT 'Auth provider.',
    EXTERNAL_ID     VARCHAR(190) NULL COMMENT 'User id at the provider (e.g., Google sub).',
    EMAIL           VARCHAR(320) NOT NULL COMMENT 'User email (unique).',
    NAME            VARCHAR(150) NOT NULL COMMENT 'User display name.',
    PICTURE_URL     VARCHAR(500) NULL COMMENT 'Profile picture URL (optional).',
    ACTIVE          BOOLEAN      NOT NULL DEFAULT TRUE COMMENT 'If false, login disabled.',
    LAST_LOGIN_AT   DATETIME NULL COMMENT 'Last successful login timestamp.',
    CREATED_AT      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Row creation time.',
    UPDATED_AT      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Row update time.',
    CONSTRAINT PK_USER_ACCOUNT PRIMARY KEY (ID_USER_ACCOUNT),
    CONSTRAINT UK_USER_ACCOUNT_EMAIL UNIQUE (EMAIL),
    CONSTRAINT UK_USER_ACCOUNT_PROVIDER_EXTID UNIQUE (PROVIDER, EXTERNAL_ID)
) ENGINE=InnoDB
  COMMENT='Application users (reporters, actors, owners).';

CREATE INDEX IDX_USER_ACCOUNT_NAME ON USER_ACCOUNT (NAME);

-- =========================
-- INCIDENT
-- =========================
CREATE TABLE INCIDENT
(
    ID_INCIDENT              BIGINT       NOT NULL AUTO_INCREMENT COMMENT 'Primary key.',
    TITLE                    VARCHAR(200) NOT NULL COMMENT 'Short incident title.',
    SERVICE                  VARCHAR(120) NOT NULL COMMENT 'Affected service/application name.',
    SEVERITY                 ENUM('SEV-1','SEV-2','SEV-3','SEV-4') NOT NULL COMMENT 'Business severity.',
    STATUS                   ENUM('OPEN','IN_ANALYSIS','CLOSED') NOT NULL DEFAULT 'OPEN' COMMENT 'Lifecycle status.',
    STARTED_AT               DATETIME     NOT NULL COMMENT 'Incident start time.',
    ENDED_AT                 DATETIME NULL COMMENT 'Incident end time (when resolved).',
    IMPACT_SHORT             VARCHAR(500) NULL COMMENT 'Brief impact summary (what/how many/how long).',
    ID_USER_ACCOUNT_REPORTER BIGINT NULL COMMENT 'User who opened/reported the incident.',
    CREATED_AT               DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Row creation time.',
    UPDATED_AT               DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Row update time.',
    CONSTRAINT PK_INCIDENT PRIMARY KEY (ID_INCIDENT),
    CONSTRAINT FK_INCIDENT_ID_USER_ACCOUNT_REPORTER
        FOREIGN KEY (ID_USER_ACCOUNT_REPORTER) REFERENCES USER_ACCOUNT (ID_USER_ACCOUNT)
            ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB
  COMMENT='Incident main record (what, where, severity, time window).';

CREATE INDEX IDX_INCIDENT_SERVICE ON INCIDENT (SERVICE);
CREATE INDEX IDX_INCIDENT_SEVERITY ON INCIDENT (SEVERITY);
CREATE INDEX IDX_INCIDENT_STATUS ON INCIDENT (STATUS);
CREATE INDEX IDX_INCIDENT_STARTED_AT ON INCIDENT (STARTED_AT);

-- =========================
-- INCIDENT_EVENT (Timeline)
-- =========================
CREATE TABLE INCIDENT_EVENT
(
    ID_INCIDENT_EVENT     BIGINT   NOT NULL AUTO_INCREMENT COMMENT 'Primary key.',
    ID_INCIDENT           BIGINT   NOT NULL COMMENT 'FK to INCIDENT.',
    EVENT_AT              DATETIME NOT NULL COMMENT 'Event timestamp.',
    TYPE                  ENUM('ALERT','DIAGNOSIS','MITIGATION','FIX','COMMUNICATION') NOT NULL COMMENT 'Timeline event type.',
    DESCRIPTION           TEXT     NOT NULL COMMENT 'Event description.',
    ID_USER_ACCOUNT_ACTOR BIGINT NULL COMMENT 'Actor who performed/reported the event.',
    CREATED_AT            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Row creation time.',
    UPDATED_AT            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Row update time.',
    CONSTRAINT PK_INCIDENT_EVENT PRIMARY KEY (ID_INCIDENT_EVENT),
    CONSTRAINT FK_INCIDENT_EVENT_ID_INCIDENT
        FOREIGN KEY (ID_INCIDENT) REFERENCES INCIDENT (ID_INCIDENT)
            ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_INCIDENT_EVENT_ID_USER_ACCOUNT_ACTOR
        FOREIGN KEY (ID_USER_ACCOUNT_ACTOR) REFERENCES USER_ACCOUNT (ID_USER_ACCOUNT)
            ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB
  COMMENT='Incident timeline: alert, diagnosis, mitigation, fix, communication.';

CREATE INDEX IDX_INCIDENT_EVENT_INCIDENT_AT ON INCIDENT_EVENT (ID_INCIDENT, EVENT_AT);
CREATE INDEX IDX_INCIDENT_EVENT_TYPE ON INCIDENT_EVENT (TYPE);
CREATE INDEX IDX_INCIDENT_EVENT_ACTOR ON INCIDENT_EVENT (ID_USER_ACCOUNT_ACTOR);

-- =========================
-- ROOT_CAUSE (5 Whys + factors)
-- =========================
CREATE TABLE ROOT_CAUSE
(
    ID_ROOT_CAUSE        BIGINT       NOT NULL AUTO_INCREMENT COMMENT 'Primary key.',
    ID_INCIDENT          BIGINT       NOT NULL COMMENT 'FK to INCIDENT (1:1).',
    WHY1                 VARCHAR(500) NOT NULL COMMENT 'Why #1.',
    WHY2                 VARCHAR(500) NOT NULL COMMENT 'Why #2.',
    WHY3                 VARCHAR(500) NOT NULL COMMENT 'Why #3.',
    WHY4                 VARCHAR(500) NOT NULL COMMENT 'Why #4.',
    WHY5                 VARCHAR(500) NOT NULL COMMENT 'Why #5.',
    ROOT_CAUSE_TEXT      VARCHAR(800) NOT NULL COMMENT 'Root cause statement.',
    CONTRIBUTING_FACTORS VARCHAR(800) NULL COMMENT 'Contributing/systemic factors.',
    LESSONS_LEARNED      TEXT NULL COMMENT 'Lessons learned (optional).',
    CREATED_AT           DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Row creation time.',
    UPDATED_AT           DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Row update time.',
    CONSTRAINT PK_ROOT_CAUSE PRIMARY KEY (ID_ROOT_CAUSE),
    CONSTRAINT FK_ROOT_CAUSE_ID_INCIDENT
        FOREIGN KEY (ID_INCIDENT) REFERENCES INCIDENT (ID_INCIDENT)
            ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT UK_ROOT_CAUSE_ID_INCIDENT UNIQUE (ID_INCIDENT)
) ENGINE=InnoDB
  COMMENT='Cause analysis: 5 Whys, root cause, contributing factors, lessons.';

CREATE INDEX IDX_ROOT_CAUSE_INCIDENT ON ROOT_CAUSE (ID_INCIDENT);

-- =========================
-- ACTION_ITEM (corrective/preventive)
-- =========================
CREATE TABLE ACTION_ITEM
(
    ID_ACTION_ITEM        BIGINT   NOT NULL AUTO_INCREMENT COMMENT 'Primary key.',
    ID_INCIDENT           BIGINT   NOT NULL COMMENT 'FK to INCIDENT.',
    TYPE                  ENUM('CORRECTIVE','PREVENTIVE') NOT NULL COMMENT 'Action type.',
    DESCRIPTION           TEXT     NOT NULL COMMENT 'Action description.',
    ID_USER_ACCOUNT_OWNER BIGINT NULL COMMENT 'Action owner (responsible person).',
    DUE_DATE              DATE NULL COMMENT 'Due date (SLA).',
    STATUS                ENUM('TODO','DOING','DONE','LATE') NOT NULL DEFAULT 'TODO' COMMENT 'Action status.',
    EVIDENCE_LINK         VARCHAR(500) NULL COMMENT 'Optional evidence link (doc/PR/board).',
    COMPLETED_AT          DATETIME NULL COMMENT 'Completion timestamp (if DONE).',
    CREATED_AT            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Row creation time.',
    UPDATED_AT            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Row update time.',
    CONSTRAINT PK_ACTION_ITEM PRIMARY KEY (ID_ACTION_ITEM),
    CONSTRAINT FK_ACTION_ITEM_ID_INCIDENT
        FOREIGN KEY (ID_INCIDENT) REFERENCES INCIDENT (ID_INCIDENT)
            ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ACTION_ITEM_ID_USER_ACCOUNT_OWNER
        FOREIGN KEY (ID_USER_ACCOUNT_OWNER) REFERENCES USER_ACCOUNT (ID_USER_ACCOUNT)
            ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB
  COMMENT='Corrective/preventive actions with owner, SLA and status.';

CREATE INDEX IDX_ACTION_ITEM_INCIDENT ON ACTION_ITEM (ID_INCIDENT);
CREATE INDEX IDX_ACTION_ITEM_OWNER ON ACTION_ITEM (ID_USER_ACCOUNT_OWNER);
CREATE INDEX IDX_ACTION_ITEM_STATUS ON ACTION_ITEM (STATUS);
CREATE INDEX IDX_ACTION_ITEM_DUE_DATE ON ACTION_ITEM (DUE_DATE);

-- =========================
-- POSTMORTEM_DOC (generated document)
-- =========================
CREATE TABLE POSTMORTEM_DOC
(
    ID_POSTMORTEM_DOC  BIGINT   NOT NULL AUTO_INCREMENT COMMENT 'Primary key.',
    ID_INCIDENT        BIGINT   NOT NULL COMMENT 'FK to INCIDENT.',
    MD_CONTENT         LONGTEXT NOT NULL COMMENT 'Markdown content of the postmortem.',
    GENERATED_AT       DATETIME NOT NULL COMMENT 'Document generation timestamp.',
    COMPLETENESS_SCORE SMALLINT NOT NULL COMMENT 'Checklist-based completeness score (0..100).',
    VERSION            INT      NOT NULL DEFAULT 1 COMMENT 'Document version (incremental).',
    CREATED_AT         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Row creation time.',
    UPDATED_AT         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Row update time.',
    CONSTRAINT PK_POSTMORTEM_DOC PRIMARY KEY (ID_POSTMORTEM_DOC),
    CONSTRAINT FK_POSTMORTEM_DOC_ID_INCIDENT
        FOREIGN KEY (ID_INCIDENT) REFERENCES INCIDENT (ID_INCIDENT)
            ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB
  COMMENT='Rendered postmortem (MD/PDF source) with completeness score and version.';

CREATE INDEX IDX_POSTMORTEM_DOC_INCIDENT ON POSTMORTEM_DOC (ID_INCIDENT);
CREATE INDEX IDX_POSTMORTEM_DOC_GENERATED ON POSTMORTEM_DOC (GENERATED_AT);
