USE
POSTMORTEM;

ALTER TABLE ROOT_CAUSE
    MODIFY COLUMN WHY1 VARCHAR (500) NULL,
    MODIFY COLUMN WHY2 VARCHAR (500) NULL,
    MODIFY COLUMN WHY3 VARCHAR (500) NULL,
    MODIFY COLUMN WHY4 VARCHAR (500) NULL,
    MODIFY COLUMN WHY5 VARCHAR (500) NULL
    MODIFY COLUMN ROOT_CAUSE_TEXT VARCHAR (800) NULL;

ALTER TABLE ACTION_ITEM
    MODIFY COLUMN DUE_DATE DATETIME NULL COMMENT 'Due date (SLA).';