USE
POSTMORTEM;

ALTER TABLE ROOT_CAUSE
    MODIFY COLUMN WHY1 VARCHAR (500) NULL,
    MODIFY COLUMN WHY2 VARCHAR (500) NULL,
    MODIFY COLUMN WHY3 VARCHAR (500) NULL,
    MODIFY COLUMN WHY4 VARCHAR (500) NULL,
    MODIFY COLUMN WHY5 VARCHAR (500) NULL
    MODIFY COLUMN ROOT_CAUSE_TEXT VARCHAR (800) NULL;

ALTER TABLE ACTION_ITEM
    MODIFY COLUMN DUE_DATE DATETIME NULL COMMENT 'Due date (SLA).';

ALTER TABLE POSTMORTEM_DOC
    ADD CONSTRAINT UK_POSTMORTEM_DOC_INCIDENT_VERSION UNIQUE (ID_INCIDENT, VERSION);

CREATE INDEX IDX_POSTMORTEM_DOC_INCIDENT_GENERATED_AT
    ON POSTMORTEM_DOC (ID_INCIDENT, GENERATED_AT DESC);